DEVICE          : cuda             # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'output/cvcclinicdb'         # output folder name used for saving the model, logs and inference results

MODEL:                                    
  NAME          : 
    - PLDSegFormer     # name of the model you are using
    - SegFormer
  BACKBONE      : 
    - MiT-B0           # model variant
    - MiT-B1
    - MiT-B2
    - MiT-B3
    - MiT-B4
    - MiT-B5
  PRETRAINED    : 
    - 'checkpoints/backbones/mit/mit_b0.pth'  # 'checkpoints/backbones/mit/mit_b0.pth'  # backbone model's weight 
    - 'checkpoints/backbones/mit/mit_b1.pth'
    - 'checkpoints/backbones/mit/mit_b2.pth'
    - 'checkpoints/backbones/mit/mit_b3.pth'
    - 'checkpoints/backbones/mit/mit_b4.pth'
    - 'checkpoints/backbones/mit/mit_b5.pth'

DATASET:
  NAME          : CVCClinicDB               # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : 'data/CVC-ClinicDB'    # dataset root path
  IGNORE_LABEL  : 255

TRAIN:
  IMAGE_SIZE    : [352, 352]      # training image size in (h, w)
  BATCH_SIZE    : 16              # batch size used to train
  EPOCHS        : 200             # number of epochs to train
  EVAL_INTERVAL : 1              # evaluation interval during training
  AMP           : true            # use AMP in training
  DDP           : false           # use DDP training

LOSS:
  NAME          : DiceLoss            # loss function name (ohemce, ce, dice)
  CLS_WEIGHTS   : false           # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.000149           # 000149 initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.1             # decay rate used in optimizer 

SCHEDULER:
  NAME          : plrd            # warmuppolylr # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 0               # 2 warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  MODEL_PATH    : 
    - 'output/cvcclinicdb/PLDSegFormer_MiT-B0_CVCClinicDB.pth'  # trained model file path
    - 'output/cvcclinicdb/PLDSegFormer_MiT-B1_CVCClinicDB.pth'  # trained model file path
    - 'output/cvcclinicdb/PLDSegFormer_MiT-B2_CVCClinicDB.pth'  # trained model file path
    - 'output/cvcclinicdb/PLDSegFormer_MiT-B3_CVCClinicDB.pth'  # trained model file path
    - 'output/cvcclinicdb/PLDSegFormer_MiT-B4_CVCClinicDB.pth'  # trained model file path
    - 'output/cvcclinicdb/PLDSegFormer_MiT-B5_CVCClinicDB.pth'  # trained model file path
    - 'output/cvcclinicdb/SegFormer_MiT-B0_CVCClinicDB.pth'  # trained model file path
    - 'output/cvcclinicdb/SegFormer_MiT-B1_CVCClinicDB.pth'  # trained model file path
    - 'output/cvcclinicdb/SegFormer_MiT-B2_CVCClinicDB.pth'  # trained model file path
    - 'output/cvcclinicdb/SegFormer_MiT-B3_CVCClinicDB.pth'  # trained model file path
    - 'output/cvcclinicdb/SegFormer_MiT-B4_CVCClinicDB.pth'  # trained model file path
    - 'output/cvcclinicdb/SegFormer_MiT-B5_CVCClinicDB.pth'  # trained model file path
  IMAGE_SIZE    : [352, 352]                                                            # evaluation image size in (h, w)                       
  MSF: 
    ENABLE      : false                                                                 # multi-scale and flip evaluation  
    FLIP        : true                                                                  # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]                                     # scales used in MSF evaluation                


TEST:
  MODEL_PATH    : 'output/PLDSegFormer_MiT-B0_CVCClinicDB.pth'  # trained model file path
  FILE          : 'data/Kvasir-SEG/train/images/cju0roawvklrq0799vmjorwfv.jpg'                                                         # filename or foldername 
  IMAGE_SIZE    : [352, 352]                                                            # inference image size in (h, w)
  OVERLAY       : true                                                                  # save the overlay result (image_alpha+label_alpha)